export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

// auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

// tournaments
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const DELETE_TOURNAMENT_SUCCESS = 'DELETE_TOURNAMENT_SUCCESS';

// tournaments for approvel
export const CREATE_TOURNAMENT_FOR_APPROVAL_SUCCESS = 'CREATE_TOURNAMENT_FOR_APPROVAL_SUCCESS';
export const GET_TOURNAMENTS_FOR_APPROVAL_SUCCESS = 'GET_TOURNAMENTS_FOR_APPROVAL_SUCCESS';
export const DELETE_TOURNAMENT_FOR_APPROVAL_SUCCESS = 'DELETE_TOURNAMENT_FOR_APPROVAL_SUCCESS';